# Generated by Django 5.1 on 2024-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=10),
        ),
    ]
