# Generated by Django 5.1 on 2024-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_admin_admin_name_alter_admin_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=128),
        ),
    ]
